### PR TITLE
Support different list formats per parameter

### PR DESCRIPTION
**Pull request by kuhnroyal**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Support different list formats per parameter in query parameters and `x-www-url-encoded` body data.

### CODE REVIEW

**Comment by wendux** [comment]
why not just remain `ListParam`? (`Param` doesn't seem necessary! )
from:
```dart
        {
          'a': Param('你好'),
          'b': ListParam<int>([5, 6], ListFormat.pipes),
          'c': Param({
            'd': Param(8),
            'e': Param({
              'a': Param(5),
              'b': ListParam<String>(['foo', 'bar'], ListFormat.csv),
              'c': ListParam<String>(['foo', 'bar'], ListFormat.ssv),
              'd': ListParam<String>(['foo', 'bar'], ListFormat.multi),
              'e': ListParam<String>(['foo', 'bar'], ListFormat.tsv),
            }),
          }),
        },
```
to: 
```dart
        {
          'a': '你好',
          'b': ListParam<int>([5, 6], ListFormat.pipes),
          'c': {
            'd': 8,
            'e': {
              'a': 5,
              'b': ListParam<String>(['foo', 'bar'], ListFormat.csv),
              'c': ListParam<String>(['foo', 'bar'], ListFormat.ssv),
              'd': ListParam<String>(['foo', 'bar'], ListFormat.multi),
              'e': ListParam<String>(['foo', 'bar'], ListFormat.tsv),
            },
          },
        },
```

**Comment by kuhnroyal** [comment]
It is not necessary and may be omitted or I can remove it if you want.
I added it because this allows to add all parameters everything in uniform manner, especially when generating the parameter list from an API specification. But I can deal without it if you don't like it.

**Comment by piggie668** [comment]
There seems to be a bug in 4.0.

'src/parareter.dart' isn't exported in dio.dart, so ListParam isn't found.  I've to add the missing line in dio.dart to get ListParam to work.
Even so, using ListFormat.csv option still generate the param where the comma character is encoded with %2C.

**Comment by kuhnroyal** [comment]
@piggie668 See https://github.com/flutterchina/dio/pull/1177

**Pull request merged**
