### PR TITLE
Fix CI after merge

### PR DESCRIPTION
**Pull request by kuhnroyal**
* don't collect test result for example app, there are no test atm
* remove usage of `unawaited` - pedantic is deprecated and the new `unawait` from the Dart SDK required Dart 2.14 which would raise the min SDK for the library
* try to prevent test not completing with Dart 2.12 because of a a wrong expectation on a `Future` - use `expectLater` instead
* re-add example test which got lost in the merge

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description

...

### CODE REVIEW

**Comment by kuhnroyal** [comment]
The basic_test ist still hanging in CI with Dart 2.12 - not sure why but it seems some Future in the native socket is already completed. I think this is related to the expectation on the future.

**Comment by kuhnroyal** [comment]
The `upload_stream_test` and `basic_test` both resolve the `http://httpbin.org/status/` URL.

**Comment by kuhnroyal** [comment]
The test problem was hot-fixed in `2.12.1` - we should require this as minimum version.
https://github.com/dart-lang/sdk/issues/45047
https://github.com/dart-lang/sdk/issues/45214

**Comment by kuhnroyal** [comment]
Seems to have worked.

@wendux Can you setup a branch protection rule for develop requiring reviews, resolutions and status checks so we ensure it remains stable from now on?

Bildschirmfoto 2021-11-28 um 19 14 50

**Comment by wendux** [comment]
I have add you as maintainer, you can do(merge、config...) it by yourself 😆

**Comment by kuhnroyal** [comment]
@wendux  Thanks! Merging this as everything is green now.
But collaborators can not configure the branch protection rules :)

**Pull request merged**
