### PR TITLE
fix platform specific import

### PR DESCRIPTION
**Pull request by VB10**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description
I want to use the web and native adapter on one page. You were adding createAdapter function but doesn't has at adapter class so this has crashed on the project build.
This can be using after this pr.
`    httpClientAdapter = createAdapter();
`
image

...

### CODE REVIEW

**Comment by jgoyvaerts** [comment]
Can you give me an example of how you can use the web and native adapter on one page? What's your build target?

**Comment by VB10** [comment]
@jgoyvaerts yep, i solve this problem on my page. You can look adapter folder in dio source then you can show adapter instance:
`import 'package:dio/src/adapters/io_adapter.dart' if (dart.library.html) 'package:dio/src/adapters/browser_adapter.dart'
    as adapter;

 httpClientAdapter = adapter.createAdapter();
`

Maybe work for u too.

**Comment by jgoyvaerts** [comment]
You're misunderstanding my question. Are you running on web? Android? iOS? The specific implementations are different for each platform (Web uses browser_adapter, Android/iOS/Windows/MacOS/Linux uses io_adapter), so how could you ever need "both" the web and native adapter on one page? You're doing something wrong then.

**Comment by jgoyvaerts** [comment]
Never mind I see what you mean. I'll fix it in my fork!

**Comment by VB10** [comment]
You know flutter works on every platform so sometimes one page work web and mobile(ios, android same works). Normally dio can handle this process but I have a library with use dio.I have a manager page then I need platform-specific implementation because this manager works web and mobile and this class works everywhere platform. So I need this pr for this usage but I found a createAdapter instance then I fixed my problems.
Library: https://pub.dev/packages/vexana
Manager: https://github.com/VB10/vexana/blob/master/lib/src/network_manager.dart

**Pull request closed without merging**
