### PR TITLE
Fix for Flutter 1.17 release

### PR DESCRIPTION
**Pull request by buzzySmile**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Fix for compatibility with Flutter 1.17 release. Request to update Dio(2.x.x) minor version in pub.

### CODE REVIEW

**Comment by uinin3x** [comment]
👍

**Comment by heath3n** [comment]
Commenting to prevent closing; this is still an issue.

**Comment by buzzySmile** [comment]
Still waiting for merge. @wendux

**Comment by heath3n** [comment]
Commenting to prevent closing; this is still an issue.

**Comment by buzzySmile** [comment]
This PR is still active and waiting for resolve.

**Comment by buzzySmile** [comment]
Still actual

**Comment by buzzySmile** [comment]
Still actual

**Comment by AzadCoder** [comment]
Still actual???

**Comment by buzzySmile** [comment]
Seems merge will never happens. Considering that Flutter 2.0 released (we should bump our projects to newer version of flutter as well as dio accordingly).
But if you still need to use this `dio` version just add to your `pubspec.yaml` git dependency from this merge source
```
dependencies:
  dio:
    git:
      url: git@github.com:buzzySmile/dio.git
      ref: 2.1.x
```

**Pull request closed without merging**
