### PR TITLE
[4.0] fix get http headers

### LINKED ISSUE #1059: Http Headers are not being recognized
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | Beta Channel 1.26.0-17.8.pre                              |      |
| Dio Version                    | 4.0.0-beta3                                  |      |
| Repro rate                     | all the time (100%) |      |
### Issue Description and Steps

The http headers are not being recognized in this new nullsafety version

### PR DESCRIPTION
**Pull request by fogaiht**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description

...

fix #1059

### CODE REVIEW

**Comment by MaxweelFreitas** [comment]
this will fix my problems too

**Comment by OrlandoEduardo101** [comment]
finally someone fixed this problem, great day! :)

**Comment by MaxweelFreitas** [comment]
This will fix my problems too

**Comment by JBDionisio** [comment]
i waiting this :)

**Comment by matheusperez** [comment]
This will fix my problems too

**Comment by toshiossada** [comment]
This will fix my problems too

**Comment by BlackLeg15** [comment]
Good job, sir. I was waiting for it.

**Comment by arthurgiani** [comment]
That's a miracle! Thank you a lot!

**Comment by vianafgbluiz** [comment]
Approve please, i need so much this.

**Comment by wendux** [comment]
fixed in 4.0.0-prev2, example: https://github.com/flutterchina/dio/blob/7534c1c9aa4577914a176e055a915b9b1220027a/dio/test/options_test.dart#L195

**Comment by fogaiht** [comment]
it not fix the problem, in GET method continue removing content-type from headers.... 

> fixed in 4.0.0-prev2, example:
> 
> https://github.com/flutterchina/dio/blob/7534c1c9aa4577914a176e055a915b9b1220027a/dio/test/options_test.dart#L195

in this test, you confirm that the headers will be always deleted in GET Method !!
it's not make sense deleting this!!

**Comment by MaxweelFreitas** [comment]
I have tested too. Really it's not solved! The fix have no link with the initial issue.

**Comment by wendux** [comment]
set `dio.options.setRequestContentTypeWhenNoPayload = true;`

**Comment by fogaiht** [comment]
@wendux, this flag works here!!!! thanks a lot!

**Comment by MaxweelFreitas** [comment]
> @fogaiht @MaxweelFreitas set `dio.options.setRequestContentTypeWhenNoPayload = true;`

thank you man. Solvev my problem :100:

**Pull request closed without merging**
