### PR TITLE
fix: dio does not properly handle the json media type

### PR DESCRIPTION
**Pull request by amondnet**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description

https://www.iana.org/assignments/media-types/media-types.xhtml
Dio does not properly handle the numerous json [media type](https://en.wikipedia.org/wiki/Media_type) registered in [iana](https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority).

- application/vnd.github+json
- [application/vnd.hal+json](https://www.iana.org/assignments/media-types/application/vnd.hal+json)
- [application/activity+json](https://www.iana.org/assignments/media-types/application/activity+json)
- [application/ld+json](https://www.iana.org/assignments/media-types/application/ld+json)
- application/calendar+json
- application/coap-group+json
- [application/geo+json](https://www.iana.org/assignments/media-types/application/geo+json)
- [application/vcard+json](https://www.iana.org/assignments/media-types/application/vcard+json)	
...

This pr fix this issue.

### CODE REVIEW

**Comment by NeoMindStd** [comment]
Excellent! it worked for Issue [#668](https://github.com/flutterchina/dio/issues/668)!
thanks for your solution.

**Comment by ACHEZ9** [comment]
Any updates on this?

**Comment by LeLunZ** [comment]
won't this be merged?

**Comment by amondnet** [comment]
ping

**Comment by amondnet** [comment]
https://github.com/flutterchina/dio/pull/1438

**Pull request closed without merging**
