### PR TITLE
fix

### PR DESCRIPTION
**Pull request by maxzod**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...
if you declare the request data type  `final res = await Dio().get<T>(....)`;
it returns nullable object T? but i have specifically told it it is not nullable when i need to be nullable i will use T? instead

this PR fixes this issues

### CODE REVIEW

**Comment by NicolaVerbeeck** [comment]
Does this PR also fix the case where T _is_ nullable, this has been broken since 4.0.1 (wrong non-null cast in dio_mixin's assureResponse)

**Comment by maxzod** [comment]
@NicolaVerbeeck  yes

**Comment by kuhnroyal** [comment]
Not sure this is the right approach. In any case, this is a breaking change as it is now required to specify `T?` for everything that previously worked.

**Comment by kuhnroyal** [comment]
While I like the idea of explicitly specifying if the response is nullable, this will be a breaking change.
We can consider this for a 5.0.0 release if there is a general consensus. I started a discussion for this: https://github.com/flutterchina/dio/discussions/1335

@NicolaVerbeeck The `T?` problem has been fixed in https://github.com/flutterchina/dio/pull/1322

**Pull request closed without merging**
