### PR TITLE
Added function to check if the current dio instance is locked

### PR DESCRIPTION
**Pull request by pedromassango**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I am adding
- [ ] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description

I just added a function to check if the current dio instance is locked it is similar to `lock` and `unlock` but to check if Dio instance is locked or not.
...

### CODE REVIEW

**Comment by pedromassango** [comment]
Not yet.

**Comment by pedromassango** [comment]
Not yet

**Comment by pedromassango** [comment]
Don't stale

**Comment by wendux** [comment]
Why not use `interceptors.requestLock.locked` directly ?

**Comment by pedromassango** [comment]
This is a proposal to simply check if dio is locked directly from the dio instance.

Anyway, it has been to long and I forgot the why I proposed this.

**Pull request closed without merging**
